# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv_rcpp <- function(mat_, tau) {
    .Call('_gpbart_inv_rcpp', PACKAGE = 'gpbart', mat_, tau)
}

pinv_rcpp <- function(mat_, tau) {
    .Call('_gpbart_pinv_rcpp', PACKAGE = 'gpbart', mat_, tau)
}

gamma_pdf <- function(x, a, b) {
    .Call('_gpbart_gamma_pdf', PACKAGE = 'gpbart', x, a, b)
}

r_gamma_pdf <- function(x, a, b) {
    .Call('_gpbart_r_gamma_pdf', PACKAGE = 'gpbart', x, a, b)
}

print_mat_subset <- function(X) {
    invisible(.Call('_gpbart_print_mat_subset', PACKAGE = 'gpbart', X))
}

log_dmvn <- function(x, Sigma) {
    .Call('_gpbart_log_dmvn', PACKAGE = 'gpbart', x, Sigma)
}

cppgpbart <- function(x_train, x_train_gp, y_train, x_test, x_test_gp, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, nu, stump_bool, sample, sample_phi, verbose, no_rotation_bool, only_rotation_bool) {
    .Call('_gpbart_cppgpbart', PACKAGE = 'gpbart', x_train, x_train_gp, y_train, x_test, x_test_gp, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, nu, stump_bool, sample, sample_phi, verbose, no_rotation_bool, only_rotation_bool)
}

mat_init <- function(n) {
    .Call('_gpbart_mat_init', PACKAGE = 'gpbart', n)
}

vec_init <- function(n) {
    .Call('_gpbart_vec_init', PACKAGE = 'gpbart', n)
}

std_inv <- function(A, diag) {
    .Call('_gpbart_std_inv', PACKAGE = 'gpbart', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_gpbart_std_pinv', PACKAGE = 'gpbart', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_gpbart_faster_simple_std_inv', PACKAGE = 'gpbart', A, diag)
}

log_test <- function(a) {
    .Call('_gpbart_log_test', PACKAGE = 'gpbart', a)
}

faster_std_inv <- function(A, diag) {
    .Call('_gpbart_faster_std_inv', PACKAGE = 'gpbart', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_gpbart_rMVN2', PACKAGE = 'gpbart', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_gpbart_rMVNslow', PACKAGE = 'gpbart', b, Q)
}

matrix_mat <- function(array) {
    .Call('_gpbart_matrix_mat', PACKAGE = 'gpbart', array)
}

